In [2]:
# Reshape a 1D array of size 9 into a 3×3 matrix

import numpy as np

arr = np.array([12,53,41,9,74,1,2,30,25])
reshape_arr = arr.reshape(3,3)
print(reshape_arr)

[[12 53 41]
 [ 9 74  1]
 [ 2 30 25]]
