In [4]:
# Apply broadcasting to add the bonus to every month's sales.
import numpy as np

sales = np.array([
    [120, 150, 180, 200],
    [100, 130, 170, 190],
    [140, 160, 200, 220]
])

bonus = np.array([10, 20, 15, 25])

bonus_added = sales + bonus
print(bonus_added)

[[130 170 195 225]
 [110 150 185 215]
 [150 180 215 245]]
