In [6]:
# Create a 3×3 array filled with random numbers and print its shape.

import numpy as np

arr = np.array([[23,20,84],[50,30,9],[14,9,108]])
print(arr)
print(arr.shape)

[[ 23  20  84]
 [ 50  30   9]
 [ 14   9 108]]
(3, 3)
